#ifndef CYGONCE_PKGCONF_REDBOOT_H
#define CYGONCE_PKGCONF_REDBOOT_H
/*
 * File <pkgconf/redboot.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#include <pkgconf/hal.h>
#define CYGSEM_REDBOOT_ELF 1
#define CYGINT_REDBOOT_LOAD_METHOD 1
#define CYGINT_REDBOOT_LOAD_METHOD_1
#define CYGNUM_REDBOOT_CMD_LINE_EDITING 16
#define CYGNUM_REDBOOT_CMD_LINE_EDITING_16
#define CYGSEM_REDBOOT_CMD_LINE_ANSI_SEQUENCES 1
#define CYGBLD_REDBOOT_CMD_LINE_HISTORY 1
#define CYGBLD_REDBOOT_MAX_MEM_SEGMENTS 1
#define CYGBLD_REDBOOT_MAX_MEM_SEGMENTS_1
#define CYGBLD_BUILD_REDBOOT_WITH_CKSUM 1
#define CYGBLD_BUILD_REDBOOT_WITH_MFILL 1
#define CYGBLD_BUILD_REDBOOT_WITH_MCMP 1
#define CYGBLD_BUILD_REDBOOT_WITH_MCOPY 1
#define CYGBLD_BUILD_REDBOOT_WITH_DUMP 1
#define CYGBLD_BUILD_REDBOOT_WITH_CACHES 1
#define CYGDBG_REDBOOT_TICK_GRANULARITY 250
#define CYGDBG_REDBOOT_TICK_GRANULARITY_250
#define CYGPKG_REDBOOT_ANY_CONSOLE 1
#define CYGPKG_REDBOOT_MAX_CMD_LINE 256
#define CYGPKG_REDBOOT_MAX_CMD_LINE_256
#define CYGNUM_REDBOOT_CLI_IDLE_TIMEOUT 10
#define CYGNUM_REDBOOT_CLI_IDLE_TIMEOUT_10
#define CYGSEM_REDBOOT_VALIDATE_USER_RAM_LOADS 1
#define CYGPKG_REDBOOT_FLASH 1
#define CYGOPT_REDBOOT_FLASH_BYTEORDER NATURAL
#define CYGOPT_REDBOOT_FLASH_BYTEORDER_NATURAL
#define CYGDAT_REDBOOT_FIS_MAX_FREE_CHUNKS 32
#define CYGDAT_REDBOOT_FIS_MAX_FREE_CHUNKS_32
#define CYGSEM_REDBOOT_FIS_CRC_CHECK 1
#define CYGINT_REDBOOT_ARM_FLASH_SIB_SUPPORTED 0
#define CYGINT_REDBOOT_ARM_FLASH_SIB_SUPPORTED_0
#define CYGPKG_REDBOOT_DISK 1
#define CYGINT_REDBOOT_DISK_DRIVERS 0
#define CYGINT_REDBOOT_DISK_DRIVERS_0
#define CYGNUM_REDBOOT_MAX_DISKS 4
#define CYGNUM_REDBOOT_MAX_DISKS_4
#define CYGNUM_REDBOOT_MAX_PARTITIONS 8
#define CYGNUM_REDBOOT_MAX_PARTITIONS_8
#define CYGSEM_REDBOOT_DISK_EXT2FS 1
#define CYGNUM_REDBOOT_BOOT_SCRIPT_TIMEOUT_RESOLUTION 1000
#define CYGNUM_REDBOOT_BOOT_SCRIPT_TIMEOUT_RESOLUTION_1000
#define CYGNUM_REDBOOT_BOOT_SCRIPT_DEFAULT_TIMEOUT 10
#define CYGNUM_REDBOOT_BOOT_SCRIPT_DEFAULT_TIMEOUT_10
#define CYGNUM_REDBOOT_GETC_BUFFER 256
#define CYGNUM_REDBOOT_GETC_BUFFER_256

#endif
