src/gps4020_flash.o.d:  \
 /opt/ecos-cvs/packages/devs/flash/arm/gps4020/current/src/gps4020_flash.c \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/cyg/io/flash_at49xxxx.inl \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/pkgconf/hal.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/pkgconf/system.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/pkgconf/hal_arm.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/pkgconf/hal_arm_gps4020.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/pkgconf/devs_flash_atmel_at49xxxx.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/cyg/hal/hal_arch.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/cyg/infra/cyg_type.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/stddef.h \
  /opt/tools/ARM34~1.3/bin/../lib/gcc/arm-elf/3.4.3/include/stddef.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/cyg/hal/basetype.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/cyg/hal/hal_cache.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/cyg/hal/hal_diag.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/cyg/hal/hal_if.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/cyg/hal/dbg-threads-api.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/cyg/hal/dbg-thread-syscall.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/stdarg.h \
  /opt/tools/ARM34~1.3/bin/../lib/gcc/arm-elf/3.4.3/include/stdarg.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/pkgconf/mlt_arm_gps4020_ram.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/cyg/io/flash.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/pkgconf/io_flash.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/cyg/io/flash_dev.h \
  /ecos-c/cygwin/home/andrew/gps/redboot/redboot_ram/redboot_ram_install/include/cyg/io/flash_at49xxxx_parts.inl
