#ifndef CYGONCE_PKGCONF_SYSTEM_H
#define CYGONCE_PKGCONF_SYSTEM_H
/*
 * File <pkgconf/system.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_VERSION_CURRENT 0x7fffff00
#define CYGPKG_HAL_ARM current
#define CYGPKG_HAL_ARM_current
#define CYGNUM_HAL_ARM_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_ARM_VERSION_MINOR -1
#define CYGNUM_HAL_ARM_VERSION_RELEASE -1
#define CYGPKG_HAL_ARM_GPS4020 current
#define CYGPKG_HAL_ARM_GPS4020_current
#define CYGNUM_HAL_ARM_GPS4020_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_ARM_GPS4020_VERSION_MINOR -1
#define CYGNUM_HAL_ARM_GPS4020_VERSION_RELEASE -1
#define CYGBLD_HAL_TARGET_H   <pkgconf/hal_arm.h>
#define CYGBLD_HAL_PLATFORM_H <pkgconf/hal_arm_gps4020.h>
#define CYG_HAL_STARTUP ROM
#define CYG_HAL_STARTUP_ROM
#define CYGHWR_MEMORY_LAYOUT_LDI <pkgconf/mlt_arm_gps4020_rom.ldi>
#define CYGHWR_MEMORY_LAYOUT_H <pkgconf/mlt_arm_gps4020_rom.h>
#define CYGPKG_DEVS_FLASH_ATMEL_AT49XXXX current
#define CYGPKG_DEVS_FLASH_ATMEL_AT49XXXX_current
#define CYGNUM_DEVS_FLASH_ATMEL_AT49XXXX_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_DEVS_FLASH_ATMEL_AT49XXXX_VERSION_MINOR -1
#define CYGNUM_DEVS_FLASH_ATMEL_AT49XXXX_VERSION_RELEASE -1
#define CYGPKG_DEVS_FLASH_GPS4020 current
#define CYGPKG_DEVS_FLASH_GPS4020_current
#define CYGNUM_DEVS_FLASH_GPS4020_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_DEVS_FLASH_GPS4020_VERSION_MINOR -1
#define CYGNUM_DEVS_FLASH_GPS4020_VERSION_RELEASE -1
#define CYGPKG_HAL current
#define CYGPKG_HAL_current
#define CYGNUM_HAL_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_VERSION_MINOR -1
#define CYGNUM_HAL_VERSION_RELEASE -1
#define CYGPKG_INFRA current
#define CYGPKG_INFRA_current
#define CYGNUM_INFRA_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_INFRA_VERSION_MINOR -1
#define CYGNUM_INFRA_VERSION_RELEASE -1
#define CYGPKG_REDBOOT current
#define CYGPKG_REDBOOT_current
#define CYGNUM_REDBOOT_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_REDBOOT_VERSION_MINOR -1
#define CYGNUM_REDBOOT_VERSION_RELEASE -1
#define CYGPKG_ISOINFRA current
#define CYGPKG_ISOINFRA_current
#define CYGNUM_ISOINFRA_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_ISOINFRA_VERSION_MINOR -1
#define CYGNUM_ISOINFRA_VERSION_RELEASE -1
#define CYGPKG_LIBC_STRING current
#define CYGPKG_LIBC_STRING_current
#define CYGNUM_LIBC_STRING_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_STRING_VERSION_MINOR -1
#define CYGNUM_LIBC_STRING_VERSION_RELEASE -1
#define CYGPKG_CRC current
#define CYGPKG_CRC_current
#define CYGNUM_CRC_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_CRC_VERSION_MINOR -1
#define CYGNUM_CRC_VERSION_RELEASE -1
#define CYGPKG_NS_DNS current
#define CYGPKG_NS_DNS_current
#define CYGNUM_NS_DNS_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_NS_DNS_VERSION_MINOR -1
#define CYGNUM_NS_DNS_VERSION_RELEASE -1
#define CYGPKG_IO_FLASH current
#define CYGPKG_IO_FLASH_current
#define CYGNUM_IO_FLASH_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_FLASH_VERSION_MINOR -1
#define CYGNUM_IO_FLASH_VERSION_RELEASE -1

#endif
