#ifndef CYGONCE_PKGCONF_HAL_ARM_GPS4020_H
#define CYGONCE_PKGCONF_HAL_ARM_GPS4020_H
/*
 * File <pkgconf/hal_arm_gps4020.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGPRI_KERNEL_TESTS_DHRYSTONE_PASSES 100000
#define HAL_PLATFORM_CPU    "ARM7TDMI"
#define HAL_PLATFORM_BOARD  "GPS-4020"
#define HAL_PLATFORM_EXTRA  ""
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_1
#define CYGNUM_HAL_RTC_CONSTANTS 1
#define CYGNUM_HAL_RTC_NUMERATOR 1000000000
#define CYGNUM_HAL_RTC_NUMERATOR_1000000000
#define CYGNUM_HAL_RTC_DENOMINATOR 100
#define CYGNUM_HAL_RTC_DENOMINATOR_100
#define CYGNUM_HAL_RTC_PERIOD 10000
#define CYGNUM_HAL_RTC_PERIOD_10000
#define CYGBLD_GLOBAL_OPTIONS 1
#define CYGSEM_HAL_USE_ROM_MONITOR GDB_stubs
#define CYGSEM_HAL_USE_ROM_MONITOR_GDB_stubs

#endif
