#ifndef CYGONCE_PKGCONF_SYSTEM_H
#define CYGONCE_PKGCONF_SYSTEM_H
/*
 * File <pkgconf/system.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_VERSION_CURRENT 0x7fffff00
#define CYGPKG_HAL current
#define CYGPKG_HAL_current
#define CYGNUM_HAL_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_VERSION_MINOR -1
#define CYGNUM_HAL_VERSION_RELEASE -1
#define CYGPKG_IO current
#define CYGPKG_IO_current
#define CYGNUM_IO_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_VERSION_MINOR -1
#define CYGNUM_IO_VERSION_RELEASE -1
#define CYGPKG_IO_SERIAL current
#define CYGPKG_IO_SERIAL_current
#define CYGNUM_IO_SERIAL_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_SERIAL_VERSION_MINOR -1
#define CYGNUM_IO_SERIAL_VERSION_RELEASE -1
#define CYGPKG_INFRA current
#define CYGPKG_INFRA_current
#define CYGNUM_INFRA_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_INFRA_VERSION_MINOR -1
#define CYGNUM_INFRA_VERSION_RELEASE -1
#define CYGPKG_KERNEL current
#define CYGPKG_KERNEL_current
#define CYGNUM_KERNEL_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_KERNEL_VERSION_MINOR -1
#define CYGNUM_KERNEL_VERSION_RELEASE -1
#define CYGPKG_MEMALLOC current
#define CYGPKG_MEMALLOC_current
#define CYGNUM_MEMALLOC_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_MEMALLOC_VERSION_MINOR -1
#define CYGNUM_MEMALLOC_VERSION_RELEASE -1
#define CYGPKG_ISOINFRA current
#define CYGPKG_ISOINFRA_current
#define CYGNUM_ISOINFRA_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_ISOINFRA_VERSION_MINOR -1
#define CYGNUM_ISOINFRA_VERSION_RELEASE -1
#define CYGPKG_LIBC current
#define CYGPKG_LIBC_current
#define CYGNUM_LIBC_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_VERSION_MINOR -1
#define CYGNUM_LIBC_VERSION_RELEASE -1
#define CYGPKG_LIBC_I18N current
#define CYGPKG_LIBC_I18N_current
#define CYGNUM_LIBC_I18N_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_I18N_VERSION_MINOR -1
#define CYGNUM_LIBC_I18N_VERSION_RELEASE -1
#define CYGPKG_LIBC_SETJMP current
#define CYGPKG_LIBC_SETJMP_current
#define CYGNUM_LIBC_SETJMP_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_SETJMP_VERSION_MINOR -1
#define CYGNUM_LIBC_SETJMP_VERSION_RELEASE -1
#define CYGPKG_LIBC_SIGNALS current
#define CYGPKG_LIBC_SIGNALS_current
#define CYGNUM_LIBC_SIGNALS_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_SIGNALS_VERSION_MINOR -1
#define CYGNUM_LIBC_SIGNALS_VERSION_RELEASE -1
#define CYGPKG_LIBC_STARTUP current
#define CYGPKG_LIBC_STARTUP_current
#define CYGNUM_LIBC_STARTUP_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_STARTUP_VERSION_MINOR -1
#define CYGNUM_LIBC_STARTUP_VERSION_RELEASE -1
#define CYGPKG_LIBC_STDIO current
#define CYGPKG_LIBC_STDIO_current
#define CYGNUM_LIBC_STDIO_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_STDIO_VERSION_MINOR -1
#define CYGNUM_LIBC_STDIO_VERSION_RELEASE -1
#define CYGPKG_LIBC_STDLIB current
#define CYGPKG_LIBC_STDLIB_current
#define CYGNUM_LIBC_STDLIB_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_STDLIB_VERSION_MINOR -1
#define CYGNUM_LIBC_STDLIB_VERSION_RELEASE -1
#define CYGPKG_LIBC_STRING current
#define CYGPKG_LIBC_STRING_current
#define CYGNUM_LIBC_STRING_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_STRING_VERSION_MINOR -1
#define CYGNUM_LIBC_STRING_VERSION_RELEASE -1
#define CYGPKG_LIBC_TIME current
#define CYGPKG_LIBC_TIME_current
#define CYGNUM_LIBC_TIME_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_TIME_VERSION_MINOR -1
#define CYGNUM_LIBC_TIME_VERSION_RELEASE -1
#define CYGPKG_LIBM current
#define CYGPKG_LIBM_current
#define CYGNUM_LIBM_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBM_VERSION_MINOR -1
#define CYGNUM_LIBM_VERSION_RELEASE -1
#define CYGPKG_IO_WALLCLOCK current
#define CYGPKG_IO_WALLCLOCK_current
#define CYGNUM_IO_WALLCLOCK_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_WALLCLOCK_VERSION_MINOR -1
#define CYGNUM_IO_WALLCLOCK_VERSION_RELEASE -1
#define CYGPKG_ERROR current
#define CYGPKG_ERROR_current
#define CYGNUM_ERROR_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_ERROR_VERSION_MINOR -1
#define CYGNUM_ERROR_VERSION_RELEASE -1
#define CYGPKG_HAL_ARM current
#define CYGPKG_HAL_ARM_current
#define CYGNUM_HAL_ARM_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_ARM_VERSION_MINOR -1
#define CYGNUM_HAL_ARM_VERSION_RELEASE -1
#define CYGPKG_HAL_ARM_GPS4020 current
#define CYGPKG_HAL_ARM_GPS4020_current
#define CYGNUM_HAL_ARM_GPS4020_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_ARM_GPS4020_VERSION_MINOR -1
#define CYGNUM_HAL_ARM_GPS4020_VERSION_RELEASE -1
#define CYGBLD_HAL_TARGET_H   <pkgconf/hal_arm.h>
#define CYGBLD_HAL_PLATFORM_H <pkgconf/hal_arm_gps4020.h>
#define CYG_HAL_STARTUP RAM
#define CYG_HAL_STARTUP_RAM
#define CYGHWR_MEMORY_LAYOUT_LDI <pkgconf/mlt_arm_gps4020_ram.ldi>
#define CYGHWR_MEMORY_LAYOUT_H <pkgconf/mlt_arm_gps4020_ram.h>
#define CYGPKG_IO_SERIAL_ARM_GPS4020 current
#define CYGPKG_IO_SERIAL_ARM_GPS4020_current
#define CYGNUM_IO_SERIAL_ARM_GPS4020_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_SERIAL_ARM_GPS4020_VERSION_MINOR -1
#define CYGNUM_IO_SERIAL_ARM_GPS4020_VERSION_RELEASE -1
/***** serial driver proc output start *****/
#define CYGDAT_IO_SERIAL_DEVICE_HEADER <pkgconf/io_serial_arm_gps4020.h>
/*****  serial driver proc output end  *****/

#endif
